In [1]:
import numpy as np


#### 1D Array

In [2]:
a=np.array([1,2,3])
print(a)

[1 2 3]


In [3]:
b=np.array([1,2,3,4,5])
b

array([1, 2, 3, 4, 5])

#### Attributes of arrays

In [4]:
a.dtype

dtype('int32')

In [5]:
a.ndim

1

In [6]:
b.size

5

In [7]:
a.shape

(3,)

#### Multidimensional array

In [8]:
m=np.array([[2,3,4],
          [3,4,5],
          [3,6,7]])
m

array([[2, 3, 4],
       [3, 4, 5],
       [3, 6, 7]])

In [9]:
m.dtype

dtype('int32')

In [10]:
m.size

9

In [11]:
m.shape

(3, 3)

In [12]:
print(m[0])

[2 3 4]


In [13]:
print(m[2][2])

7


In [14]:
print(m[0][0])

2


In [15]:
an=np.array([[2,3]])
an.shape


(1, 2)

In [16]:
n1=np.array([[[2,3,4,5]]])

In [17]:
n1.shape

(1, 1, 4)

In [18]:
n2=np.array([[[2,3,4],[5,6,7]]])

In [19]:
n2.shape

(1, 2, 3)

In [20]:
n3=np.array([[2,3,4],[5,6,7],[7,8,9]],dtype=float)
n3

array([[2., 3., 4.],
       [5., 6., 7.],
       [7., 8., 9.]])

#### Bigger Arrays

In [21]:
big=np.array([
    [[1,2,3],[2,4,5],[8,9,0]],
    [[3,5,7],[5,7,8],[1,6,7]],
    [[2,4,6],[5,7,9],[0,1,4]]],dtype=float)
big

array([[[1., 2., 3.],
        [2., 4., 5.],
        [8., 9., 0.]],

       [[3., 5., 7.],
        [5., 7., 8.],
        [1., 6., 7.]],

       [[2., 4., 6.],
        [5., 7., 9.],
        [0., 1., 4.]]])

In [22]:
big.shape

(3, 3, 3)

In [23]:
big.ndim

3

In [24]:
big.size

27

In [25]:
big[2][1][1]

7.0

In [26]:
big[2][2][2]

4.0

### Filling arrays

#### By using the full function for example, we fill an array of a certain shape with the same number. In this case we create a 3x5x4 matrix, which is filled with sevens. 

In [27]:
afull=np.full((3,4,3),2)
afull

array([[[2, 2, 2],
        [2, 2, 2],
        [2, 2, 2],
        [2, 2, 2]],

       [[2, 2, 2],
        [2, 2, 2],
        [2, 2, 2],
        [2, 2, 2]],

       [[2, 2, 2],
        [2, 2, 2],
        [2, 2, 2],
        [2, 2, 2]]])

In [28]:
afull.ndim

3

In [29]:
bfull=np.full((2,2,2),9)
bfull

array([[[9, 9],
        [9, 9]],

       [[9, 9],
        [9, 9]]])

### Zeros and Ones

#### For the cases that we want arrays full of zeros or ones, we even have specific functions. 


In [30]:
a0=np.zeros((2,3))
a0

array([[0., 0., 0.],
       [0., 0., 0.]])

In [31]:
a0=np.zeros((4,2,5))
a0

array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]])

In [32]:
a1=np.ones((3,3,3))
a1

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

In [33]:
a1=np.ones((4,4,2))
a1

array([[[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]]])

### Empty and Random

#### Other options would be to create an empty array or one that is filled with random numbers. For this, we use the respective functions once again. 


In [34]:
e=np.empty((4,2,4))
e

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [35]:
ran=np.random.random((3,4,5))
ran

array([[[0.91628975, 0.6067752 , 0.84351756, 0.71737082, 0.64942914],
        [0.26769877, 0.91433551, 0.52812769, 0.80343671, 0.54952437],
        [0.42232801, 0.67661942, 0.60833588, 0.94402646, 0.86484821],
        [0.02741434, 0.9567708 , 0.56208533, 0.90256966, 0.76984305]],

       [[0.56913659, 0.95977928, 0.22812232, 0.13564494, 0.29733849],
        [0.38502535, 0.78113324, 0.48316936, 0.24901853, 0.14504309],
        [0.25134795, 0.04883456, 0.17127889, 0.17564501, 0.51660123],
        [0.43309228, 0.18890194, 0.50350747, 0.76879205, 0.62998551]],

       [[0.27315569, 0.66526508, 0.10922232, 0.67167936, 0.3494232 ],
        [0.75533758, 0.6769294 , 0.43208258, 0.63295541, 0.70306118],
        [0.7830914 , 0.58632691, 0.1854243 , 0.84200478, 0.01654841],
        [0.29643777, 0.40914065, 0.82099576, 0.6808036 , 0.1175528 ]]])

In [36]:
ran.size

60

### Ranges

#### Instead of just filling arrays with the same values, we can fill create sequences of values by specifying the boundaries. For this, we can use two different functions, namely arange and linspace. 


### Arange

In [40]:
x = np.empty((4,3,4))

#### (start,stop,step)

In [43]:
a_arange=np.arange(2,10,3)
a_arange

array([2, 5, 8])

In [44]:
a_arange=np.arange(1,100,2)
a_arange

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61, 63, 65, 67,
       69, 71, 73, 75, 77, 79, 81, 83, 85, 87, 89, 91, 93, 95, 97, 99])

### linspace

#### By using linspace we also create a list from a minimum value to a maximum value. But instead of specifying the step-size, we specify the amount of values that we want to have in our list. They will all be spread evenly and have the same distance to their neighbors. 


### (start,stop,no.of items)

In [46]:
a_linspace=np.linspace(0,5,10)
a_linspace

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [47]:
a_linspace.size

10

In [48]:
a_linspace.ndim

1

In [50]:
a_linspace=np.linspace(0,100,10)
a_linspace

array([  0.        ,  11.11111111,  22.22222222,  33.33333333,
        44.44444444,  55.55555556,  66.66666667,  77.77777778,
        88.88888889, 100.        ])

In [51]:
a_linspace.size

10

In [52]:
a_linspace.ndim

1

In [53]:
a_linspace=np.linspace(0,100,10,dtype=int)
a_linspace

array([  0,  11,  22,  33,  44,  55,  66,  77,  88, 100])

In [54]:
m=np.array([[2,3,4],
          [3,4,5],
          [3,6,7]])
m


array([[2, 3, 4],
       [3, 4, 5],
       [3, 6, 7]])

### Math Functions

#### np.exp(a) 
Takes e to the power of each value 


In [56]:
np.exp(m)

array([[   7.3890561 ,   20.08553692,   54.59815003],
       [  20.08553692,   54.59815003,  148.4131591 ],
       [  20.08553692,  403.42879349, 1096.63315843]])

#### np.sin(a) 
Returns the sine of each value 


In [57]:
np.sin(m)

array([[ 0.90929743,  0.14112001, -0.7568025 ],
       [ 0.14112001, -0.7568025 , -0.95892427],
       [ 0.14112001, -0.2794155 ,  0.6569866 ]])

#### np.cos(a) 
Returns the cosine of each value 


In [58]:
np.cos(m)

array([[-0.41614684, -0.9899925 , -0.65364362],
       [-0.9899925 , -0.65364362,  0.28366219],
       [-0.9899925 ,  0.96017029,  0.75390225]])

#### np.tan(a) 
Returns the tangent of each value 


In [59]:
np.tan(m)

array([[-2.18503986, -0.14254654,  1.15782128],
       [-0.14254654,  1.15782128, -3.38051501],
       [-0.14254654, -0.29100619,  0.87144798]])

#### np.log(a) 
Returns the logarithm of each value 


In [60]:
np.log(m)

array([[0.69314718, 1.09861229, 1.38629436],
       [1.09861229, 1.38629436, 1.60943791],
       [1.09861229, 1.79175947, 1.94591015]])

#### np.sqrt(a) 
Returns the square root of each value 


In [61]:
np.sqrt(m)

array([[1.41421356, 1.73205081, 2.        ],
       [1.73205081, 2.        , 2.23606798],
       [1.73205081, 2.44948974, 2.64575131]])

### AGGREGATE FUNCTIONS 


In [63]:
m.sum()#return sum of all values in the array

37

In [64]:
m.min() 
#Returns the lowest value of the array 


2

In [66]:
m.max() 
#Returns the highest value of the array 


7

In [68]:
m.mean() 
#Returns the arithmetic mean of all values in the array 


4.111111111111111

In [70]:
np.median(m) 
#Returns the median value of the array 


4.0

In [73]:
np.std(m) 
#Returns the standard deviation of the values in the array 


1.5234788000891208